### PR TITLE
Added close button on the alert and 5px margin on left right

### PR DESCRIPTION
**Pull request by SouravMoitra**
My first commit to the project and I thought the alert little better if the alert have little padding and close button and little cleanup of lash_messages

### CODE REVIEW

**Comment by cpg** [comment]
can you show a screenshot (like before/after) so we have a quicker way to determine what's up in this change?

**Comment by SouravMoitra** [comment]
screenshot from 2015-01-09 22 10 31

After commit

**Comment by SouravMoitra** [comment]
screenshot from 2015-01-09 22 13 48

Before commit

**Comment by cpg** [comment]
my view is that the close button is good. but the margin, to be proper, should be aligned like thishttps://dl.dropboxusercontent.com/u/364883/Images/smaller-margins.png

note however, we do not have bootstrap in this branch. the bootstrap branch has that. we plan to merge that to master, so maybe do that there?

**Comment by SouravMoitra** [comment]
This was improved in PR #110 hence closed

**Pull request closed without merging**
