### PR TITLE
Bootstrap

### PR DESCRIPTION
**Pull request by sbagroy986**
Bootstrap implemented without loss of functionality

### CODE REVIEW

**Comment by agmps17** [comment]
Hi Shrey,

Could you see why the travis build failed. I will try and review the pull request latest by this weekend. Meanwhile just check for the reason of travis build failure.

**Comment by sbagroy986** [comment]
Hi,
I was having a problem with this.
Yesterday, I made 2 PRs. These are the travis logs of both :
1. bootstrap PR - https://travis-ci.org/amahi/platform/jobs/45912405
2. w3c validations PR - https://travis-ci.org/amahi/platform/jobs/45976993

The second one got merged.

However, when I run bundle exec rspec spec/  locally, i get the same result
for both (42 examples, 41 failures, 1 pending), but the failure details are
completely different from those in the travis logs.

Thanks for the help.

On Tue, Jan 6, 2015 at 9:00 AM, Arpit Goyal <notifications@github.com>
wrote:

> Hi Shrey,
>
> Could you see why the travis build failed. I will try and review the pull
> request latest by this weekend. Meanwhile just check for the reason of
> travis build failure.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/amahi/platform/pull/107#issuecomment-68821579>.
>



-- 
Thanks,
Shrey Bagroy

**Comment by sbagroy986** [comment]
Hi,
So I fixed most of the errors with the addition and proper routing of the CSS file. The only error remaining  now is related to Capybara ( Capybara::Poltergeist::TimeoutError:) . Since I am not familiar with Capybara at all, I'm not sure how to fix this error.

**Comment by cpg** [comment]
At least one of the build in ruby 2.1 passed. It may be a timeout in the infrastructure. Looking.

**Comment by cpg** [comment]
Actually,

1) some spurious log files were added. Please pay attention to details when you commit.
2) Do we really need the gphlyicons files?!?!

**Comment by sbagroy986** [comment]
The log files are the travis log files which got added in the second last commit. I thought I hadn't pushed them. Sorry about that.
The font (glyphicon) files are a part of the official bootstrap distribution package. We don't need them now, but it is possible they may be needed as a part of bootstrap in the future.

**Comment by cpg** [comment]
Is the spacing in app/views/layouts/_subheader.html.slim, plugins/010-users/app/views/users/settings.html.slim and plugins/050-network/app/views/network/aliases.html.slim  correct?

looking at the diff, it seems the space is not proper for slim.

the other thing i notice is that there are a couple of instances of div.foobar where just .foobar is enough. in slim, just putting a class .foobar or a item #foobar automatically puts a  div. (search for "div." in the diff)

other than the above, it looks good.

**Comment by sbagroy986** [comment]
Fixed the indentation. 

As far as I have used them, it seems one can use div.foobar or .foobar interchangeably without any problems. Also, most of the div tags seem to have already been a part of the code .I have added 2 - one  in _footer and _header. Since i am using the 'style' tags with them, they aren't replaceable by a '.'

**Pull request merged**
