### PR TITLE
Customize DHCP Lease Range

### PR DESCRIPTION
**Pull request by AhmedKamal1432**
implement this feature https://bugs.amahi.org/issues/1696

### CODE REVIEW

**Comment by cpg** [comment]
Looks good looking at the code, except the app will probably not propagate those settings to the system. This may have to be changed in hda-ctl or something like that, then also trigger a message in it to be able to pick up and propagate the settings.

**Comment by cpg** [comment]
Also, a screenshot would be great to see it better :)

**Comment by AhmedKamal1432** [comment]
these are screanshoots
dhcp_range_1
dhcp_range_2

**Comment by cpg** [comment]
The formatting of the fields in the UI is not good. in particular the labels. It should be proper (and localized). It also should look friendly.

Finally, is there validation?

The low cannot be lower than 1, it has to provide a range of at least 10 numbers (i am not sure if allowing the range to be smaller, up to 1 or even 0, is of any use.

And the high cannot be higher than 254.

**Comment by AhmedKamal1432** [comment]
I updated the two commits with validation and new view
@cpg,  could you review it 
these are new screenshots
range 1
range 2

**Comment by AhmedKamal1432** [comment]
this is the new ui @cpg 
good
good 2

**Pull request merged**
